# Generated by Django 5.1.2 on 2025-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, upload_to='menu_pictures'),
        ),
    ]
