# Generated by Django 5.1.2 on 2025-10-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0002_menuitem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, upload_to='menu/menu_pictures'),
        ),
    ]
