# Generated by Django 5.2.3 on 2025-10-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0004_alter_menuitem_description_alter_menuitem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='menu_pictures/'),
        ),
    ]
